# Generated by Django 5.1.7 on 2025-03-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                help_text="Specific permissions for this user.",
                related_name="userauths_users_permissions",
                related_query_name="userauths_user_permission",
                to="auth.permission",
            ),
        ),
    ]
